<?php
/** File 23-only settings and activation evidence template. */
defined( 'ABSPATH' ) || exit;
$title_id = $instance_id . '-settings-title';
?>
<section class="spdb-operations-section" aria-labelledby="<?php echo esc_attr( $title_id ); ?>">
	<p class="spdb-eyebrow"><?php esc_html_e( 'File 23 settings only', 'sabri-publishing-dashboard' ); ?></p><h2 id="<?php echo esc_attr( $title_id ); ?>"><?php esc_html_e( 'Settings and Activation Readiness', 'sabri-publishing-dashboard' ); ?></h2>
	<p><?php esc_html_e( 'These settings cannot grant native publishing authority, replace File 20 Safe Mode, alter File 19 delivery ownership, or self-accept a provider for production.', 'sabri-publishing-dashboard' ); ?></p>
	<form class="spdb-action-form spdb-operations-panel" data-spdb-operation-form data-endpoint="settings" data-method="POST">
		<div class="spdb-form-grid"><label><span><?php esc_html_e( 'Analytics minimum cohort', 'sabri-publishing-dashboard' ); ?></span><input type="number" name="analytics_min_cohort" min="2" max="100" value="<?php echo esc_attr( (string) $settings_result['analytics_min_cohort'] ); ?>"></label><label><span><?php esc_html_e( 'Export expiry hours', 'sabri-publishing-dashboard' ); ?></span><input type="number" name="export_ttl_hours" min="1" max="72" value="<?php echo esc_attr( (string) $settings_result['export_ttl_hours'] ); ?>"></label><label><span><?php esc_html_e( 'Maximum export rows', 'sabri-publishing-dashboard' ); ?></span><input type="number" name="max_export_rows" min="100" max="10000" value="<?php echo esc_attr( (string) $settings_result['max_export_rows'] ); ?>"></label><label><span><?php esc_html_e( 'Jobs per run', 'sabri-publishing-dashboard' ); ?></span><input type="number" name="jobs_per_run" min="1" max="25" value="<?php echo esc_attr( (string) $settings_result['jobs_per_run'] ); ?>"></label><label><span><?php esc_html_e( 'Maximum job attempts', 'sabri-publishing-dashboard' ); ?></span><input type="number" name="job_max_attempts" min="1" max="10" value="<?php echo esc_attr( (string) $settings_result['job_max_attempts'] ); ?>"></label></div>
		<label><input type="checkbox" name="automation_enabled" value="1" <?php checked( ! empty( $settings_result['automation_enabled'] ) ); ?>> <?php esc_html_e( 'Enable previously reviewed automation rules', 'sabri-publishing-dashboard' ); ?></label><label><input type="checkbox" name="ai_assistance_enabled" value="1" <?php checked( ! empty( $settings_result['ai_assistance_enabled'] ) ); ?>> <?php esc_html_e( 'Enable optional File 16 assistance', 'sabri-publishing-dashboard' ); ?></label><label><input type="checkbox" name="local_projection_pause" value="1" <?php checked( ! empty( $settings_result['local_projection_pause'] ) ); ?>> <?php esc_html_e( 'Pause File 23 local projection processing', 'sabri-publishing-dashboard' ); ?></label><button type="submit" class="spdb-button"><?php esc_html_e( 'Save Settings', 'sabri-publishing-dashboard' ); ?></button>
	</form>
	<section class="spdb-operations-panel"><h3><?php esc_html_e( 'Activation Readiness', 'sabri-publishing-dashboard' ); ?></h3><?php if ( empty( $activation_state['steps'] ) ) : ?><p><?php esc_html_e( 'Activation evidence service is unavailable.', 'sabri-publishing-dashboard' ); ?></p><?php else : ?><ul class="spdb-readiness-list"><?php foreach ( $activation_state['steps'] as $step ) : ?><li><span><?php echo esc_html( $step['label'] ); ?></span><strong><?php echo ! empty( $step['ready'] ) ? esc_html__( 'Ready', 'sabri-publishing-dashboard' ) : esc_html__( 'Pending', 'sabri-publishing-dashboard' ); ?></strong></li><?php endforeach; ?></ul><?php endif; ?><p class="spdb-caption"><?php esc_html_e( 'Hostinger staging, real-role browser testing, LiteSpeed privacy, backup/restore/rollback and Founder acceptance remain external evidence gates.', 'sabri-publishing-dashboard' ); ?></p>
		<?php if ( function_exists( 'wp_get_environment_type' ) && 'production' !== wp_get_environment_type() && empty( $activation_state['staging_accepted'] ) ) : ?>
			<form class="spdb-action-form" data-spdb-operation-form data-endpoint="activation" data-method="POST" data-confirm="true"><label><span><?php esc_html_e( 'Staging evidence identifier', 'sabri-publishing-dashboard' ); ?></span><input type="text" name="evidence_id" maxlength="191" required></label><label><span><?php esc_html_e( 'Acceptance reason', 'sabri-publishing-dashboard' ); ?></span><textarea name="reason" maxlength="500" required></textarea></label><label><input type="checkbox" name="founder_accepted" value="1"> <?php esc_html_e( 'Founder has accepted the completed staging matrix', 'sabri-publishing-dashboard' ); ?></label><button type="submit" class="spdb-button"><?php esc_html_e( 'Record Staging Evidence', 'sabri-publishing-dashboard' ); ?></button></form>
		<?php endif; ?>
	</section>
	<div class="spdb-live-region" role="status" aria-live="polite" data-spdb-operation-status></div>
</section>
